### ISSUE TITLE
doesn't match

### ISSUE THREAD

**Issue by fabiov** [gsingh93/regex-search#17]
Hi, I'm looking for a unit price (€/kg) into this page:
http://www.zooplus.it/shop/cani/snack_masticare_cani/biscotti_secchi

I tried the follow regular expression:
- /€ [0-9]{1,2},[0-9]{2}/ (works)
- /€ [0-9]{1,2},[0-9]{2}.*kg/ (doesn't work)

Thanks, Fabio.

**Comment by gsingh93** [comment]
@ComFreek's fix works, closing.
