### ISSUE TITLE
Non-functional

### ISSUE THREAD

**Issue by tommilligan** [gsingh93/regex-search#20]
Extension is currently non functional (multiple reports on Chrome Webstore, possibly dating back to Dec 14). Extension still fails to work after page refresh.

05/05/2015
Regex Search Version 1.7
Chrome Version 42.0.2311.135 m

**Comment by gsingh93** [comment]
I need to know which pages it doesn't work on and what queries you tried.

**Comment by tommilligan** [comment]
Hey,

I've tried on variety of pages, I was just going to have a look through 
the source actually as I could do with learning node.js at some point. 
One example is:

http://www.nodebeginner.org/
Searching for "/The/" and "The" both return no results.

There is a yellow box that says "Searching..." appearing briefly in the 
top-left corner of the window, but no other error messages etc.

Tom

**Comment by gsingh93** [comment]
Oh, when I open the developer console and try it out, I get an error from within the jquery library. Same thing happens on other pages. Googling shows similar errors that started showing up one or two months ago. I'm going to guess that something changed in the way jQuery works that broke this.

I'll see if I can figure out the problem or a workaround.

**Comment by gsingh93** [comment]
So there was some change that prevented you from calling `.display()` on a text node. The patch is pushed to the dev branch, I'll merge it to master and release version 1.8 soon.
