### ISSUE TITLE
Doesn't search webpage sources

### ISSUE THREAD

**Issue by lethargilistic** [gsingh93/regex-search#21]
I noticed this a short while ago and just checked with the new update. If you look at a page's source in-browser (such as with Ctrl+U), you cannot search the source with the extension. To confirm this, just open this page's source, and look for your name, not even with metacharacters. You'll be able to find it with Ctrl+F, but not with Regex Search.

**Comment by gsingh93** [comment]
I'm not sure what you mean by '', but if you're talking about pages that start with `view-source:`, then I've looked into this and I believe it isn't possible. The Chrome extension API doesn't allow for it.

**Comment by lethargilistic** [comment]
Sorry, I was trying to use Markdown on each of those keyboard shortcuts and didn't preview it. Had to rush away. ^^; If it's not possible, then it's not possible, I guess.

**Comment by gsingh93** [comment]
Also related: https://github.com/gsingh93/regex-search/issues/7
