### ISSUE TITLE
Only works on some pages

### ISSUE THREAD

**Issue by hyrmedia** [gsingh93/regex-search#22]
It seems to work here on GitHub and on a few other pages I've tried, but on most pages, when I type some text into the box (which is visible on the page) and then hit "Next" it doesn't do anything. I don't get a "x of y matches" box in the top left corner, and nothing gets highlighted. I checked the F12 console on both the pages and the background page, and there's no error message or anything.

Chrome Version: 43.0.2357.81 m
Today's Date: June 3, 2015
Extension ID: bcdabfmndggphffkchfdcekcokmbnkjl
Extension Version: 1.8

**Comment by gsingh93** [comment]
Saying "Most pages" isn't really helpful. I need the a specific page and specific regex that doesn't work. If there's a bug that's not related to https://github.com/gsingh93/regex-search/issues/8, I'll look into it.

**Comment by gsingh93** [comment]
I'm closing since there hasn't been any response.
