### ISSUE TITLE
Need an explicit license

### ISSUE THREAD

**Issue by adamcrume** [gsingh93/regex-search#31]
The project needs an explicit open source license.

**Comment by gsingh93** [comment]
Good point. I'd like to use an MIT license. I believe I need all contributors to confirm that this is OK.

@ComFreek, are you alright with this?

**Comment by NateTheGreat68** [comment]
I would fully support the MIT license for this project.

**Comment by ComFreek** [comment]
@gsingh93 Sure 👍
