### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by ComFreek** [gsingh93/regex-search#5]
The default keyboard shortcut Alt+Shift+F does not work because it is (probably) already reserved.

As this [answer on StackOverflow](http://stackoverflow.com/a/18559164/603003) explains, it is needed to navigate to the extensions page and to manually set a shortcut.

This behavior should be mentioned in `install.html` and `update.html`. What do you think?

**Comment by sl5net** [comment]
please add to main description: hwoto usw shortcut.
please add a link to the extension options to shortcuts.
thanks.
